.TH pd 1 "1996 Mar 20" GNU
.SH NAME
pd \- pure data
.SH DESCRIPTION
Pd is a graphical programming environment for real-time audio synthesis
and related applications.  It sports a rich set of real-time control
and I/O features.
.PP
To get a list of allowable arguments to pd, type
.IP
.B pd -help
.PP
and for more documentation either start pd and get help, or consult
.PP
.B http://www.crca.ucsd.edu/~msp/Pd_documentation/index.htm
.PP
or seek a copy on your own machine, perhaps in
.PP
.B file:/usr/local/bin/pd/doc/1.manual/index.htm
.PP
or
.PP
.B file:/usr/bin/pd/doc/1.manual/index.htm
.SH SEE ALSO
pdsend(1), pdreceive(1)
