.TH pdsend 1 "1996 Mar 20" GNU
.SH NAME
pdsend \- send messages to pd on this or a remote machine
.SH SYNOPSIS
.B pdsend
\fIport-number\fR [\fIhostname\fR] [udp|tcp]
.SH DESCRIPTION
Pdsend sends messages to pd(1), via a socket connection, from pdsend's
standard input.  This input can be any stream of Pd messages separated by
semicolons.  This is probably the easiest way to control pd from another
application.  The protocol used is easy to implement and is called FUDI.
.PP
The \fIport number\fR should agree with the port number of a "netreceive" object
within pd.  The \fIhostname\fR is "localhost" by default and can be a domain
name or an IP address.  The protocol is "tcp" by default; this does a handshake
to
guarantee that all messages arrive complete and in their correct order; if you
are sending messages locally or point-to-point you can often get away with
the faster udp protocol instead.
.PP
You can also use this to talk to a Max "pdnetreceive" object or even just a
"pdreceive" in another shell.  If you're writing another program you're welcome
to just grab the sources for pdsend/pdreceive and adapt them to your own ends;
they're part of the Pd distribution.
.SH SEE ALSO
pd(1), pdreceive(1)
