# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded apple_events 0.1 [list source [file join $dir apple_events.tcl]]
package ifneeded pd_bindings 0.1 [list source [file join $dir pd_bindings.tcl]]
package ifneeded pd_connect 0.1 [list source [file join $dir pd_connect.tcl]]
package ifneeded dialog_array 0.1 [list source [file join $dir dialog_array.tcl]]
package ifneeded dialog_audio 0.1 [list source [file join $dir dialog_audio.tcl]]
package ifneeded dialog_canvas 0.1 [list source [file join $dir dialog_canvas.tcl]]
package ifneeded dialog_data 0.1 [list source [file join $dir dialog_data.tcl]]
package ifneeded dialog_find 0.1 [list source [file join $dir dialog_find.tcl]]
package ifneeded dialog_font 0.1 [list source [file join $dir dialog_font.tcl]]
package ifneeded dialog_gatom 0.1 [list source [file join $dir dialog_gatom.tcl]]
package ifneeded dialog_iemgui 0.1 [list source [file join $dir dialog_iemgui.tcl]]
package ifneeded dialog_message 0.1 [list source [file join $dir dialog_message.tcl]]
package ifneeded dialog_midi 0.1 [list source [file join $dir dialog_midi.tcl]]
package ifneeded dialog_path 0.1 [list source [file join $dir dialog_path.tcl]]
package ifneeded dialog_startup 0.1 [list source [file join $dir dialog_startup.tcl]]
package ifneeded helpbrowser 0.1 [list source [file join $dir helpbrowser.tcl]]
package ifneeded opt_parser 0.1 [list source [file join $dir opt_parser.tcl]]
package ifneeded pd_guiprefs 0.1 [list source [file join $dir pd_guiprefs.tcl]]
package ifneeded pdwindow 0.1 [list source [file join $dir pdwindow.tcl]]
package ifneeded pd_menucommands 0.1 [list source [file join $dir pd_menucommands.tcl]]
package ifneeded pd_menus 0.1 [list source [file join $dir pd_menus.tcl]]
package ifneeded pdtk_canvas 0.1 [list source [file join $dir pdtk_canvas.tcl]]
package ifneeded pdtk_text 0.1 [list source [file join $dir pdtk_text.tcl]]
package ifneeded pdtk_textwindow 0.1 [list source [file join $dir pdtk_textwindow.tcl]]
package ifneeded scrollbox 0.1 [list source [file join $dir scrollbox.tcl]]
package ifneeded scrollboxwindow 0.1 [list source [file join $dir scrollboxwindow.tcl]]
package ifneeded wheredoesthisgo 0.1 [list source [file join $dir wheredoesthisgo.tcl]]
