#!/bin/sh
#usage: ./build 0.38-0 or 0.38-0test4

if test x$1 == x
then
   echo usage: ./build 0.38-0 or 0.38-0test4
   exit 1
fi

if test -d Pd-$1.app
then
    chmod -R 777 Pd-$1.app
    rm -rf Pd-$1.app
fi

tar xzf stuff/wish-shell.tgz
mv "Wish Shell.app" Pd-$1.app
cd Pd-$1.app/Contents
chmod 755 .
rm -f Info.plist
cp -p  ../../stuff/Info.plist .
cd MacOS
chmod 755 .
mv "Wish Shell" Pd
cd ..
cd Resources
chmod 755 .
rm -f Wish.icns
cp -p ../../../stuff/pd.icns ../../../stuff/pd-file.icns .
mv "Wish Shell.rsrc" Pd.rsrc
tar xzf ../../../pd-$1.src.tar.gz
mv pd-$1/* .
rmdir pd-$1
cd src
JACK=true make -f makefile.mac
cd ..
ln -s tcl Scripts
cd ../../..
pwd
chmod 755 Pd-$1.app
touch Pd-$1.app
chmod 555 Pd-$1.app/Contents Pd-$1.app
tar czf pd-$1.mac.tar.gz Pd-$1.app
