# Makefile to build class 'helloworld' for Pure Data.
# Needs Makefile.pdlibbuilder as helper makefile for platform-dependent build
# settings and rules.

# library name
lib.name = stdout

# input source file (class name == source file basename)
class.sources = stdout.c

# all extra files to be included in binary distribution of the library
datafiles = stdout-help.pd

# include Makefile.pdlibbuilder
PDLIBBUILDER_DIR=../pd-lib-builder/
include $(PDLIBBUILDER_DIR)/Makefile.pdlibbuilder
