/* IMPORTANT: EDIT m_class_dispatcher.c INSTEAD OF THIS FILE */
typedef void (*t_vfun00)(void);
typedef void (*t_vfun01)(t_floatarg d0);
typedef void (*t_vfun10)(t_int i0);
typedef void (*t_vfun02)(t_floatarg d0, t_floatarg d1);
typedef void (*t_vfun11)(t_int i0, t_floatarg d0);
typedef void (*t_vfun20)(t_int i0, t_int i1);
typedef void (*t_vfun03)(t_floatarg d0, t_floatarg d1, t_floatarg d2);
typedef void (*t_vfun12)(t_int i0, t_floatarg d0, t_floatarg d1);
typedef void (*t_vfun21)(t_int i0, t_int i1, t_floatarg d0);
typedef void (*t_vfun30)(t_int i0, t_int i1, t_int i2);
typedef void (*t_vfun04)(t_floatarg d0, t_floatarg d1, t_floatarg d2, t_floatarg d3);
typedef void (*t_vfun13)(t_int i0, t_floatarg d0, t_floatarg d1, t_floatarg d2);
typedef void (*t_vfun22)(t_int i0, t_int i1, t_floatarg d0, t_floatarg d1);
typedef void (*t_vfun31)(t_int i0, t_int i1, t_int i2, t_floatarg d0);
typedef void (*t_vfun40)(t_int i0, t_int i1, t_int i2, t_int i3);
typedef void (*t_vfun05)(t_floatarg d0, t_floatarg d1, t_floatarg d2, t_floatarg d3, t_floatarg d4);
typedef void (*t_vfun14)(t_int i0, t_floatarg d0, t_floatarg d1, t_floatarg d2, t_floatarg d3);
typedef void (*t_vfun23)(t_int i0, t_int i1, t_floatarg d0, t_floatarg d1, t_floatarg d2);
typedef void (*t_vfun32)(t_int i0, t_int i1, t_int i2, t_floatarg d0, t_floatarg d1);
typedef void (*t_vfun41)(t_int i0, t_int i1, t_int i2, t_int i3, t_floatarg d0);
typedef void (*t_vfun50)(t_int i0, t_int i1, t_int i2, t_int i3, t_int i4);
typedef t_pd *(*t_fun00)(void);
typedef t_pd *(*t_fun01)(t_floatarg d0);
typedef t_pd *(*t_fun10)(t_int i0);
typedef t_pd *(*t_fun02)(t_floatarg d0, t_floatarg d1);
typedef t_pd *(*t_fun11)(t_int i0, t_floatarg d0);
typedef t_pd *(*t_fun20)(t_int i0, t_int i1);
typedef t_pd *(*t_fun03)(t_floatarg d0, t_floatarg d1, t_floatarg d2);
typedef t_pd *(*t_fun12)(t_int i0, t_floatarg d0, t_floatarg d1);
typedef t_pd *(*t_fun21)(t_int i0, t_int i1, t_floatarg d0);
typedef t_pd *(*t_fun30)(t_int i0, t_int i1, t_int i2);
typedef t_pd *(*t_fun04)(t_floatarg d0, t_floatarg d1, t_floatarg d2, t_floatarg d3);
typedef t_pd *(*t_fun13)(t_int i0, t_floatarg d0, t_floatarg d1, t_floatarg d2);
typedef t_pd *(*t_fun22)(t_int i0, t_int i1, t_floatarg d0, t_floatarg d1);
typedef t_pd *(*t_fun31)(t_int i0, t_int i1, t_int i2, t_floatarg d0);
typedef t_pd *(*t_fun40)(t_int i0, t_int i1, t_int i2, t_int i3);
typedef t_pd *(*t_fun05)(t_floatarg d0, t_floatarg d1, t_floatarg d2, t_floatarg d3, t_floatarg d4);
typedef t_pd *(*t_fun14)(t_int i0, t_floatarg d0, t_floatarg d1, t_floatarg d2, t_floatarg d3);
typedef t_pd *(*t_fun23)(t_int i0, t_int i1, t_floatarg d0, t_floatarg d1, t_floatarg d2);
typedef t_pd *(*t_fun32)(t_int i0, t_int i1, t_int i2, t_floatarg d0, t_floatarg d1);
typedef t_pd *(*t_fun41)(t_int i0, t_int i1, t_int i2, t_int i3, t_floatarg d0);
typedef t_pd *(*t_fun50)(t_int i0, t_int i1, t_int i2, t_int i3, t_int i4);
