#!/bin/sh

#usage: ./make-release <version>
if test x$1 == x
then
   echo usage: ./make-release 0.34-0 or 0.35-0test11 or ...
   exit 1
fi

# set -x
cd ..
ROOTDIR=`pwd`
find . \( -name ".[azA-Z]*" \! -name ".git" \
    -o -name "core" -o -name "core.*" -o -name "*.cache" \) \
    -ok rm -r {} \;

cd src
sh ../linux/detab-src.sh
cd ../extra
sh ../linux/detab-src.sh
cd ..

TMPPD=/tmp/pd-$1
rm -rf /tmp/pd $TMPPD
mkdir $TMPPD
cp -pR README.txt LICENSE.txt INSTALL.txt src doc extra man \
    portaudio portmidi $TMPPD
mkdir $TMPPD/obj $TMPPD/bin
cd $TMPPD/src
autoconf
make distclean
rm -rf autom4te.cache
rm -f *.pd
cd /tmp
tar cf - pd-$1 | gzip > $ROOTDIR/archive/dist/pd-$1.src.tar.gz
rm -rf $TMPPD
ls -l $ROOTDIR/archive/dist/pd-$1.src.tar.gz
