#!/bin/sh

#usage: ./make-nodoc 0.34-0 or 0.35-0test11 or 0.37-1test6
if test x$1 == x
then
   echo usage: ./make-nodoc 0.34-0 or 0.35-0test11 or 0.37-1test6
   exit 1
fi

set -x
cd ..
ROOTDIR=`pwd`
find . \( -name ".[a-zA-Z]*" -o -name "core*" -o -name "*.cache" \) \
    -ok rm -r {} \;

cd src
sh ../linux/detab-src.sh
cd ../tcl
sh ../linux/detab-src.sh
cd ../extra
sh ../linux/detab-src.sh
cd ..

TMPPD=/tmp/pd-$1
rm -rf /tmp/pd $TMPPD
mkdir $TMPPD
cp -a README.txt LICENSE.txt INSTALL.txt src tcl extra man \
    portaudio portmidi $TMPPD
mkdir $TMPPD/doc
mkdir $TMPPD/doc/7.stuff
mkdir $TMPPD/doc/7.stuff/tools
cp doc/7.stuff/tools/testtone.pd $TMPPD/doc/7.stuff/tools

mkdir $TMPPD/obj $TMPPD/bin
cd $TMPPD/src
autoconf
make distclean
rm -rf autom4te.cache
rm *.pd
cd /tmp
tar cf - pd-$1 | gzip > $ROOTDIR/archive/dist/pd-$1.src.tar.gz
mv pd-$1 pd
tar cf - pd | gzip > /usr/src/redhat/SOURCES/pd.tar.gz
# rm -rf /tmp/pd $TMPPD
ls -l $ROOTDIR/archive/dist/pd-$1.src.tar.gz
